{{- if and .Values.metrics.enabled .Values.metrics.podScrape.enabled -}}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "hyundai-monitor.fullname" . }}
  labels:
    {{- include "hyundai-monitor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hyundai-monitor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.podScrape.interval }}
{{- end }}
